# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-22 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztour', '0002_auto_20180222_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='smallimage',
            old_name='description',
            new_name='desc',
        ),
    ]
