# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-22 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztour', '0003_auto_20180222_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
