# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-02 08:42
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ztour', '0004_quickcontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickContact',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
