# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-12 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztour', '0005_auto_20180302_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='promote',
            field=models.BooleanField(default=True),
        ),
    ]
