# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-21 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztour', '0006_post_promote'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='position',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
